### ISSUE TITLE
TODO list for a v1

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/monorepo#243]
This issue is supposed to be a collection of tasks to be completed for a v1 release. As each task is fleshed out, it should move to its own issue in the Carrot project and v1 milestone.

~~Landing page ownership~~ https://github.com/carrot-kpi/v1-monorepo/issues/244
~~Align design of landing page with the dapp (might require some UI library work to take stuff from the landing page)~~ https://github.com/carrot-kpi/v1-monorepo/issues/249

- [x] Run more tests especially on edge cases (@milan should have already ran a comprehensive test suite, but it's never enough)
- [ ] Get some launch partners (???)
- [x] Setup legal entity
- [ ] Subscribe where needed through the legal entity (DigitalOcean and Fathom for example)
- [x] Create org emails
- [ ] Finish writing a first version of the documentation
- [x] Determine which links/sections have to stay or go in both the landing page (for example in the footer) and the dapp (again, the footer)
- [ ] Stuff to do with socials?
- [ ] Anything needed for branding?
